// <auto-generated />
using Cuisine;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cuisine.Migrations
{
    [DbContext(typeof(Contexte))]
    partial class ContexteModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Cuisine.Plat", b =>
                {
                    b.Property<int>("PlatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("NbrBouchee")
                        .HasColumnType("int");

                    b.Property<string>("TypePlat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlatId");

                    b.ToTable("Plats");
                });
#pragma warning restore 612, 618
        }
    }
}
